[book]
authors = ["Youjie Zheng"]
language = "cn"
multilingual = false
src = "src"
title = "Graduation Design Report by Azure-stars"
[rust]
edition = "2024"
[output.html.playpen]
editable = true
[output.html]
git-repository-url = "https://github.com/Azure-stars/GraduationDesignReport"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
# mathjax-support = true
# [preprocessor.mathjax]
# renderers = ["html"]
[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
